services:
  test_runner:
    build: .
    env_file:
      - .env
    networks:
      - skeleton_api
    restart: "no"  # One execution only
    volumes:
      - ./reports:/app/reports # Map host to container to extract report

networks:
  skeleton_api:
    external: true
