services:
  test_runner:
    build: .
    env_file:
      - .env
    user: "${HOST_UID}:${HOST_GID}" # Run as Jenkins user to avoid permission issues
    networks:
      - skeleton_api
    restart: "no"  # One execution only
    volumes:
      - ${PWD}/reports:/app/reports # Map host to container to extract report
    environment:
      # Put pytest’s cache in a world-writable location
      - PYTEST_CACHE_DIR=/tmp/.pytest_cache

networks:
  skeleton_api:
    external: true
